
export const projects = [
  {
    title: "JSON Placeholder",
    text: "React ile oluşturulmuş JSON Placeholder APİ uygulaması.",
    img: "/img/18.png",
    github: "https://github.com/asmaydn28/json-placeholder-react-app",
    netlify: "https://asimaydin18.netlify.app/",
  },
  {
    title: "DND-Todo",
    text: "React ile oluşturulmuş sürükle bırak yapılacaklar listesi uygulaması.",
    img: "/img/17.png",
    github: "https://github.com/asmaydn28/DnD-Todo",
    netlify: "https://asimaydin17.netlify.app/",
  },
  {
    title: "Shopping List",
    text: "React ile oluşturulmuş Alışveriş listesi uygulaması.",
    img: "/img/16.png",
    github: "https://github.com/asmaydn28/shopping-list",
    netlify: "https://asimaydin16.netlify.app/",
  },
  {
    title: "React ToDo App",
    text: "React ile oluşturulmuş basit bir yapılacaklar listesi uygulaması.",
    img: "/img/15.png",
    github: "https://github.com/asmaydn28/react-todo-app",
    netlify: "https://asimaydin15.netlify.app/",
  },
  {
    title: "First React Project",
    text: "React ile oluşturulmuş İlk projem.",
    img: "/img/14.png",
    github: "https://github.com/asmaydn28/first-react-project",
    netlify: "https://asimaydin14.netlify.app/",
  },
  {
    title: "User Profile Fetcher",
    text: "API'den kullanıcı verilerini çekerek dinamik kartlar halinde görüntüleyen bir uygulamadır.",
    img: "/img/13.png",
    github: "https://github.com/asmaydn28/user-profile-fetcher",
    netlify: "https://asimaydin13.netlify.app/",
  },
  {
    title: "Starwars Filter Card",
    text: "Bu proje, bir butona basıldığında ekrana belirli kartları getiren ve üst kısmında bulunan radyo butonları ile filtreleme yapmayı sağlayan bir uygulamadır.",
    img: "/img/12.jpg",
    github: "https://github.com/asmaydn28/starwars-filter-card",
    netlify: "https://asimaydin12.netlify.app/",
  },
  {
    title: "JS Tab Switcher",
    text: "Bu proje, JavaScript ve Bootstrap kullanarak dinamik bir sekme (tab) geçişi sağlar.",
    img: "/img/11.jpg",
    github: "https://github.com/asmaydn28/JS-Tab-Switcher",
    netlify: "https://asimaydin11.netlify.app/",
  },
  {
    title: "Simple Football Scoreboard",
    text: "Basit bir JavaScript uygulaması ile futbol takımlarının isimlerini değiştirebilir ve skorlarını güncelleyebilirsiniz.",
    img: "/img/10.jpg",
    github: "https://github.com/asmaydn28/simple-football-scoreboard",
    netlify: "https://asimaydin10.netlify.app/",
  },
  {
    title: "Simple Counter App",
    text: "Basit bir JavaScript sayaç uygulaması. Bir butona tıklayarak sayacı artırabilirsiniz.",
    img: "/img/9.jpg",
    github: "https://github.com/asmaydn28/simple-counter-app",
    netlify: "https://asimaydin9.netlify.app/",
  },
  {
    title: "Bootstrap Crypto Dashboard",
    text: "Bu proje, Bootstrap 5 ve Sass kullanılarak geliştirilmiş bir Crypto App web sitesidir.",
    img: "/img/8.jpg",
    github: "https://github.com/asmaydn28/bootstrap-crypto-dashboard",
    netlify: "https://asimaydin8.netlify.app/",
  },
  {
    title: "Bootstrap Linkedin Clone",
    text: "Bu proje, Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş LinkedIn'in resmi web sitesinin bir klonudur.",
    img: "/img/7.jpg",
    github: "https://github.com/asmaydn28/bootstrap-linkedin-clone",
    netlify: "https://asimaydin7.netlify.app/",
  },
  {
    title: "Amazon Clone Bootstrap",
    text: "Bu proje, Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş Amazon'un resmi web sitesinin bir klonudur.",
    img: "/img/6.jpg",
    github: "https://github.com/asmaydn28/amazon-clone-bootstrap",
    netlify: "https://asimaydin6.netlify.app/",
  },
  {
    title: "Ecommerce Bootstrap Template",
    text: "Bu proje, küçük bir e-ticaret mağazası için Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş bir web sitesi şablonudur.",
    img: "/img/5.jpg",
    github: "https://github.com/asmaydn28/ecommerce-bootstrap-template",
    netlify: "https://asimaydin5.netlify.app/",
  },
  {
    title: "Starbucks Clone Website",
    text: "Bu proje, Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş Starbucks'ın resmi web sitesinin bir klonudur.",
    img: "/img/4.jpg",
    github: "https://github.com/asmaydn28/starbucks-clone-website",
    netlify: "https://asimaydin4.netlify.app/",
  },
  {
    title: "Modern Corporate Website",
    text: "Bu proje, modern işletmeler için Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş bir kurumsal web sitesi şablonudur.",
    img: "/img/3.jpg",
    github: "https://github.com/asmaydn28/modern-corporate-website",
    netlify: "https://asimaydin3.netlify.app/",
  },
  {
    title: "Business Bootstrap Template",
    text: "Bu proje, Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş bir iş (business) temasıdır.",
    img: "/img/2.jpg",
    github: "https://github.com/asmaydn28/business-bootstrap-template",
    netlify: "https://asimaydin2.netlify.app/",
  },
  {
    title: "App Showcase Bootstrap Template",
    text: "Bu proje, Bootstrap 5, HTML ve CSS kullanılarak geliştirilmiş bir uygulama tanıtım sitesi şablonudur.",
    img: "/img/1.jpg",
    github: "https://github.com/asmaydn28/app-showcase-bootstrap",
    netlify: "https://asimaydin1.netlify.app/",
  },
];
